apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraft-manager
  namespace: mine
  labels:
    app: minecraft-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-manager
  template:
    metadata:
      labels:
        app: minecraft-manager
    spec:
      containers:
      - name: minecraft-manager
        image: bnookala/kubekraft-manager
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /data
            name: minecraft-data
        ports:
          - containerPort: 5000
      volumes:
        - name: minecraft-data
          azureFile:
            secretName: azure-secret
            shareName: minecraft-munaged
            readOnly: false