apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraft-manager
  namespace: mine
  labels:
    app: minecraft-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-manager
  template:
    metadata:
      labels:
        app: minecraft-manager
    spec:
      containers:
      - name: api
        image: bnookala/kubekraft-manager
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
        volumeMounts:
          - mountPath: /data
            name: minecraft-data
        ports:
          - name: manager
            containerPort: 5000
      - name: web
        image: bnookala/kubekraft-manager-web
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
        volumeMounts:
          - mountPath: /data
            name: minecraft-data
        ports:
          - name: web
            containerPort: 5001
      volumes:
        - name: minecraft-data
          azureFile:
            secretName: azure-secret
            shareName: minecraft-munaged
            readOnly: false