kind: Service
apiVersion: v1
metadata:
  name: manager-svc
  namespace: mine
  labels:
    app: minecraft-manager
spec:
  type: LoadBalancer
  selector:
    app: minecraft-manager
  ports:
  - protocol: TCP
    name: minecraft-manager
    port: 5000
    targetPort: 5000
  - protocol: TCP
    name: minecraft-manager-web
    port: 5001
    targetPort: 5001