apiVersion: v1
kind: Pod
metadata:
    name: templatemepod
    namespace: mine
    labels:
        app: minecraft-pod
        serverName: templatemepod
spec:
    containers:
    - name: minecraft-server
      image: openhack/minecraft-server:2.0
      env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: SPIGOT
        - name: SPIGOT_DOWNLOAD_URL
          value: "https://cdn.getbukkit.org/spigot/spigot-1.12.2.jar"
        - name: MAX_WORLD_SIZE
          value: "1000"
        - name: DIFFICULTY
          value: "peaceful"
        - name: MAX_PLAYERS
          value: "100"
        - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
          value: "false"
        - name: GENERATE_STRUCTURES
          value: "false"
        - name: SPAWN_ANIMALS
          value: "false"
        - name: SPAWN_MONSTERS
          value: "false"
        - name: SPAWN_NPCS
          value: "false"
        - name: PVP
          value: "false"
        - name: MODE
          value: "creative"
        - name: VIEW_DISTANCE
          value: "5"
      volumeMounts:
        - mountPath: /data
          name: minecraft-data
          subPath: templatemepod
      ports:
        - containerPort: 25565
        - containerPort: 25575
        - containerPort: 9225
    volumes:
      - name: minecraft-data
        azureFile:
          secretName: azure-secret
          shareName: minecraft-munaged
          readOnly: false