FROM python:latest

COPY ./requirements.txt ./

# Python
RUN pip install -r requirements.txt

# Node
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash
RUN apt-get install -y build-essential nodejs

COPY ./package.json ./
RUN npm install

ADD . .
RUN npm run build
RUN npm install -g serve

EXPOSE 5001

# Flask API on 5000, React SPA on 5001
CMD serve -s build -p 5001